//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by zip32j.rc
//
#define IDD_DIALOG_PASSWORD             101
#define IDD_DIALOG_STATUS               102
#define IDD_DIALOG_COMMENT              103
#define IDC_EDIT_PASS1                  1000
#define IDC_EDIT_PASS2                  1001
#define IDC_EDIT_STATUS                 1002
#define IDC_EDIT_COMMENT                1003

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1004
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
